# Generated by Django 3.1.7 on 2021-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_search_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
