# Generated by Django 3.1.7 on 2021-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
