# Generated by Django 3.1.7 on 2021-02-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210222_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
        migrations.RemoveField(
            model_name='search',
            name='expiration_date',
        ),
    ]
