# Generated by Django 3.1.7 on 2021-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210222_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
