# Generated by Django 3.1.7 on 2021-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
