# Generated by Django 3.1.7 on 2021-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210223_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
