# Generated by Django 3.1.7 on 2021-02-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20210223_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='availability',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
