# Generated by Django 3.1.7 on 2021-02-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20210223_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='zipcode',
        ),
    ]
